# Generated by Django 5.2 on 2025-05-18 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='product_imgs/')),
                ('slug', models.CharField(max_length=400)),
                ('price', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('categoryProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
                ('colorProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.color')),
                ('markProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.mark')),
                ('sizeProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.size')),
            ],
        ),
    ]
