# Generated by Django 5.2 on 2025-05-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=50)),
                ('forca', models.IntegerField()),
                ('destreza', models.IntegerField()),
                ('inteligencia', models.IntegerField()),
                ('carisma', models.IntegerField()),
            ],
        ),
    ]
