# Generated by Django 5.2 on 2025-05-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='experiencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='classe',
            field=models.CharField(max_length=100),
        ),
    ]
