# Generated by Django 5.2 on 2025-05-09 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0002_personagem_experiencia_personagem_nivel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesafioCenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('acao', models.CharField(max_length=50)),
                ('dificuldade', models.IntegerField()),
                ('resolvido', models.BooleanField(default=False)),
                ('sucesso', models.BooleanField(blank=True, null=True)),
                ('dado', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('personagem_resolveu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jogo.personagem')),
            ],
        ),
    ]
