# Generated by Django 5.2 on 2025-04-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruta',
            name='qtd',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
