# Generated by Django 5.2 on 2025-04-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frutas', '0002_fruta_qtd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruta',
            name='qtd',
            field=models.IntegerField(null=True),
        ),
    ]
